### ISSUE TITLE
[Request] Firefox port

### ISSUE THREAD

**Issue by mietzen** [dedoussis/icloud-hide-my-email-browser-extension#10]
Hi, 
first of all thank you for this extension! But I got a request, would you port this extension to firefox?
I've got 0 Javascript and browser extension developing experience, so I think I'll not be able to do this by myself.
I only read that this (in general) shouldn't be to complicated: https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

Is this also the case for your extension? If true would you be Interested to port this extension to firefox?

**Comment by dedoussis** [comment]
Hi @mietzen, thank you for the feedback!

I've been thinking about porting this extension to Firefox for quite some time now. Unfortunately, it's not as simple as publishing the same package to Firefox. There are some minor browser API incompatibilities that I need to address first. I'm planning to find some time in the next couple of weeks and get this done.

**Comment by dedoussis** [comment]
Firefox compatibility (which essentially means Manifest Version 2 compatibility) has been merged to main. I have submitted the extension to the add-on marketplace of Firefox and is awaiting a review. Will update this thread, once the extension is reviewed and available for install.

**Comment by dedoussis** [comment]
@mietzen The extension has been approved: https://addons.mozilla.org/en-US/firefox/addon/icloud-hide-my-email/
