### ISSUE TITLE
Extension seems to break apple.com logins

### ISSUE THREAD

**Issue by tlancina** [dedoussis/icloud-hide-my-email-browser-extension#30]
Hey there, thanks for building this! I haven't debugged the issue at all, but I noticed that having this extension activated seems to subtly break all apple.com logins (appleid, developer and support all had different errors/behaviors) in different ways. Just opening an issue as a heads up.

**Comment by dedoussis** [comment]
Thanks for taking the time to report this @tlancina! I haven't been able to reproduce this. Would you be able to provide some steps to reproduce as well as some specs of your local setup (OS, browser, browser version, extension version).

**Comment by dedoussis** [comment]
@tlancina I've pushed a fix for this. The new version (`1.1.1`) is currently being published in both the Chrome and the Firefox webstores. Hope you give the extension another try 😃

**Comment by tlancina** [comment]
Thanks for the fix! I’ll give it a shot and let you know if I have any
issues.
