### ISSUE TITLE
Autofill new emails only on plugin (apple) press

### ISSUE THREAD

**Issue by mattangelofdeth** [dedoussis/icloud-hide-my-email-browser-extension#31]
I love this extension, thanks for creating it.

A helpful addition would be the option to not have the plugin autofill every email field unless the apple is pressed.

**Comment by dedoussis** [comment]
Hi @mattangelofdeth! You can disable the autofilling via button in the [Options page](https://github.com/dedoussis/icloud-hide-my-email-browser-extension?tab=readme-ov-file#options) of the extension. Let me know if you have trouble founding this page.
