### ISSUE TITLE
add support for hardware key (2fa) login

### ISSUE THREAD

**Issue by henkisdabro** [dedoussis/icloud-hide-my-email-browser-extension#41]
I use Yubikey's on my iCloud account, so on icloud.com when I sign in I'm prompted the username and password as well as a subsequent prompt from my operating system to authenticate using my Yubikey. When I try logging into the extension, it instead just prompts me for a 2-factor six-digit code, which does not exist, and I can't log in.

**Comment by Ponjimon** [comment]
Duplicate of #26

**Comment by dedoussis** [comment]
Thanks for submitting this issue @henkisdabro! Just a heads up that I've been working on a change that will enable security keys. I plan to publish it by EOW.

**Comment by henkisdabro** [comment]
Amazing! Can't wait!

**Comment by robigan** [comment]
+1

**Comment by dedoussis** [comment]
Chrome one also got the approval!

**Comment by robigan** [comment]
Been using it the past week, works fine.

**Comment by dedoussis-stripe** [comment]
Great, closing this.
