### ISSUE TITLE
Can support custom domain?

### ISSUE THREAD

**Issue by bibicadotnet** [dedoussis/icloud-hide-my-email-browser-extension#46]
Apple currently supports creating custom domains from iCloud

Can I add it to use `domain.com` or `sub.domain.com` as an alternative email to `@icloud.com`?

**Comment by dedoussis** [comment]
Hi @bibicadotnet! 

Is this question about generating HideMyEmail addresses that end in `@domain.com` instead of `@icloud.com`? This feature is currently not supported by the HideMyEmail service of Apple (i.e. it's not a limitation of the extension).
