### ISSUE TITLE
Brave - keeps prompting to sign in

### ISSUE THREAD

**Issue by jamescrowley** [dedoussis/icloud-hide-my-email-browser-extension#55]
This extension works great in Edge, but in Brave the extension keeps prompting to sign in to iCloud even when I am signed in.

**Comment by dedoussis** [comment]
Hi @jamescrowley! Thanks for reporting this! I personally use the extension on the brave browser and have not noticed any such issue.

I suspect that the icloud.com authentication state of the extension has got out of sync with the authentication state of the browser.

Would you mind sharing:
1. The version of brave you're using
2. The version of the extension

**Comment by jamescrowley** [comment]
@dedoussis that was it, thanks!
