### ISSUE TITLE
Setting to hide notifications

### ISSUE THREAD

**Issue by kotx** [dedoussis/icloud-hide-my-email-browser-extension#71]
Get one on every startup of the browser, maybe only show it once after login?

**Comment by dedoussis-stripe** [comment]
@kotx thanks for reporting this issue. The intension is to only show it after icloud.com login. What browser, browser version, and extension version are you on?

**Comment by dedoussis-stripe** [comment]
@kotx if you are on firefox, the issue should have been fixed as of version 1.2.9 of the extension.

**Comment by kotx** [comment]
Seems to have been fixed. Thanks!
